### ISSUE TITLE
Generate /docs output from the repo /docs folder

### ISSUE THREAD

**Issue by palvarez89** [CodethinkLabs/immut#10]
The idea would be to use a post commit hook

**Comment by Zarathecat** [comment]
I think this should work now; will check it tomorrow and hopefully we can then mark this closed.

**Comment by Zarathecat** [comment]
This does work, although as noted on irc:

16:26 < Zara> have confirmed docs gen works; if the very first commit in a repo 
              is the docs dir, the hook won't run; I think it doesn't work when 
              the repo is empty.

so this is something to look at in the future.
