### ISSUE TITLE
yarn/cmdtest seems to be a pre-requisite

### ISSUE THREAD

**Issue by devcurmudgeon** [CodethinkLabs/immut#2]
and can we document how to get/install all pre-requisites?

**Comment by fishface60** [comment]
`sudo apt-get install cmdtest`

Newer debians will let you `sudo apt install yarn`.

**Comment by danielsilverstone-ct** [comment]
It's also worth noting that the origin of yarn is documented in the README.  Admittedly at the bottom, but it's there.

**Comment by palvarez89** [comment]
Yes, `python-cmdtest` tool is used for tests, but this, and any other tools (like docker, ostree, rpm-ostree, ...)  are not  pre-requisites to use the scripts that we are creating in `immut.git`.

The only pre-requisites needed are `packer` and `VirtualBox` (or `qemu`). All other requirements will be installed in the virtual machines created by these tools.
